### ISSUE TITLE
Error: "Error: Unable to load configuration file "config/mediatypes.json"!"

### ISSUE THREAD

**Issue by seanvree** [Tensai75/plpp#1]
OS: Windows 10E X64 1709 FCU
Webserver: IIS 10
PHP V: PHP 7.1.11 (cli) (built: Oct 25 2017 20:54:15) ( NTS MSVC14 (Visual C++ 2015) x64 )
PMS: Version 1.11.0.4666

Issue:  Settings creation went without error. it can access PLEX, and get generate the libraries in the settings page.   I can access the settings page just fine, but when I go to the Frontend I get the error below.  I can still access the settings.php page fine. 

```
Error: Unable to load configuration file "config/mediatypes.json"!
```
No erros in the DOM.  That file is NOT located in the config dir?

Also, I have the OLD version running fine and it has no mediatypes.json file in the webroot dir. 

Debug: 
(I can access the below URLs fine)

```
$plexURL = Array
(
    [0] => http://localhost:32400/library/sections?X-Plex-Token=removed
    [1] => http://localhost:32400/library/recentlyAdded?X-Plex-Token=removed
)

$plppItem = 
$plppItemType = 
$plppViewgroupType = 
$plppViewmode = slider
$plppItemsFilter = 
$plppItemsQuery = 
Token = removed

Array
(
    [size] => 6
    [allowSync] => 0
    [identifier] => com.plexapp.plugins.library
    [mediaTagPrefix] => /system/bundle/media/flags/
    [mediaTagVersion] => 1514437190
    [title1] => Plex Library
    [items] => 
)

Array
(
)

```
![image](https://user-images.githubusercontent.com/8906637/34469001-ec112784-eec9-11e7-995a-f82ccebc5bd5.png)

**Comment by D4rk56** [comment]
Same error

**Comment by Tensai75** [comment]
I am so sorry. I forgot to include the mediatypes.json in the release, the only config file which is not auto-generated by the settings.php script. Should be solved now.

**Comment by seanvree** [comment]
@Tensai75  something is still off. Trying to dbug now. I'll give you some data here in a bit.

**Comment by seanvree** [comment]
@Tensai75  yeah, all I get is a blank page now. No errors in the dom or debug console.  Is it supposed to be creating that mediatypes.json  in the /config dir? Because I still don't have that file anywhere in install dir.  


![image](https://user-images.githubusercontent.com/8906637/34472807-d2010986-ef1e-11e7-835f-c164501a3f76.png)

**Comment by D4rk56** [comment]
CP mediatypes in /config. Solved

**Comment by Tensai75** [comment]
Hi Sean

Please go to the settings.php and check whether your libraries show up in the "Libraries" settings under "Excluded libraries". For me it looks like you have selected all libraries:
![excluded libraries](https://user-images.githubusercontent.com/34959627/34477695-4d266eb2-ef9c-11e7-95e8-a550ee36c58d.jpg)
Only those libraries you DON'T want to be shown should be selected.

Regards!

**Comment by seanvree** [comment]
@Tensai75  wow, I'm an idiot.

**Comment by Tensai75** [comment]
Don't bother, you are not the first one with this issue :-)

I first thought of having it the other way round, so you would have to check those libraries you actually want to show. But then I probably would have had even more support questions from those who forgot to check the libraries they want to show.

**Comment by seanvree** [comment]
Ha, thanks!

**Comment by Tensai75** [comment]
@seanvree 
I have now also added a [FAQ](https://github.com/Tensai75/plpp/wiki/Frequently-Asked-Questions-(FAQ)) to the plpp wiki and your issue has the honour to be the first topic :-)
Hopefully the people will actually read it ....

**Comment by seanvree** [comment]
Proud to be the first jerk in the room ;)
