### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by wuast94** [Tensai75/plpp#13]
I installed this in a docker container..don't see any errors and in settings I can select the library's I have so the connection should be fine.

But in overview I have a blank screen..only search and settings on the left side

**Comment by Tensai75** [comment]
Please check the FAQ:
https://github.com/Tensai75/plpp/wiki/Frequently-Asked-Questions-(FAQ)#after-installing-and-setting-up-the-script-the-index-page-only-shows-a-blank-screen
