### ISSUE TITLE
NEW EPISODES instead of NEW SEASONS

### ISSUE THREAD

**Issue by cyb3rgh05t** [Tensai75/plpp#14]
Hi,

this is not really an issue, but i am wondering if it could be possible to change on the home screen to show newly added episodes instead of newly added seasons?

or if you could point me in the right way to edit this? i am new to php and so on :)

Thanks in advance

**Comment by Tensai75** [comment]
Sorry that I never commented on your question.
But this has zero priority for me and to implement such a feature goes certainly beyond the knowledge of a PHP novice. So if I would take the time to guide you through this, I could have done it probably myself in the same time.

**Comment by cyb3rgh05t** [comment]
alright thank you
