### ISSUE TITLE
Specific section not able to load

### ISSUE THREAD

**Issue by XtremeCoder007** [Tensai75/plpp#15]
Hi,

I can view all sections except movies, it loads a long time and then displays a error message :"operation timed out after 10001 milliseconds with x out of x bytes received."

Tried to increase php memory limit as some suggest with this issue however the php doesnt seem to apply this.

Kind regards,

XtremeCoder

**Comment by Tensai75** [comment]
Hmm, seems like the request of the plpp script to get the XML library list from the plex server is timing out.

Can you tell a little more about your particular set-up?
Where is your plex server installed and where the plpp script?
What is the uplink connection speed from the plex server to the server where plpp is installed?
And how many movies are in your movie section?

I have about 1250 movies in my largest library which results in about 2.5 MB of XML data which needs to be sent from the plex server to plpp. This should be no problem at all neither for plex nor plpp to handle it on decent hardware and with a decent uplink connection of the plex server.

Edit: You could also try to increase the timeout value from 10 to 30 or higher in the following lines:
https://github.com/Tensai75/plpp/blob/0ff9de51b7de493db0782c4232c0b2eb63d0545b/php/class.plexAPI.php#L594
https://github.com/Tensai75/plpp/blob/0ff9de51b7de493db0782c4232c0b2eb63d0545b/php/class.plexAPI.php#L595

**Comment by XtremeCoder007** [comment]
I've tried to increase those to even 120 seconds.

I have about 17000 movies, so that might cause the issue ?

Kind regards,

XtremeCoder007

**Comment by Tensai75** [comment]
17000!?! And I thought my collection is big :-)
So in your case this is probably about 30 MB or more of XML data which needs to be transferred in one request and then processed by the plpp script. This might simply be too much causing the time out.

So unfortunately I have no solution for you. I will probably tackle this issue once my own collection has grown this big that I run into the same problem. But for the time being I honestly have no time to address this.

**Comment by XtremeCoder007** [comment]
you can check the affected section here:
[Movies](http://plexdirectory.tk/index.php?item=1&type=library)

I've increased many settings:
[PHP Settings](http://plexdirectory.tk/phpinfo.php)

Say i would implement a different function, how would you tackle this issue in general, i might further work on that.

Thanks anyway for the reponse,

XtremeCoder

**Comment by Tensai75** [comment]
I would probably introduce some kind of lazy loading or a pagination. The Plex API gives you the posibility to request only a certain amount of items per library. This can be done with the additional parameters X-Plex-Container-Start and X-Plex-Container-Size. The following request will only return the first 20 items of the library with the key 1:

`https://your-plex-server.com:32400/library/sections/1/all?X-Plex-Token=xxxxxxxxxxxx&X-Plex-Container-Start=0&X-Plex-Container-Size=20`

Lazy loading could probably easily be included into and would work fine with the thumbnail view mode. But for the list view mode, the whole functionality of the table (pagination, search, ordering) which is currently conveniently done by the JS plugin would probably all have to be coded in PHP.

Regards, Tensai
