### ISSUE TITLE
White screen for movie library, rest load correctly

### ISSUE THREAD

**Issue by shutchi2** [Tensai75/plpp#18]
The main page and all of my libraries load correctly except for my movies, which shows a white screen and never finishes loading. I thought it was because of the number of movies but my music library loads and it's much larger. Any ideas?

**Comment by shutchi2** [comment]
After 45 minutes issue corrected itself.

**Comment by shutchi2** [comment]
Now getting this error:

http://127.0.0.1:32400/library/sections/1/all?X-Plex-Token=XXXXXXXXXXXXXXXXXXXXOperation timed out after 10001 milliseconds with 0 bytes received

**Comment by Tensai75** [comment]
See #15
