### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by saitoh183** [Tensai75/plpp#6]
Does a docker image exist for this? I would want to use it with https://github.com/jwilder/nginx-proxy but im not use how i can when it is not a docker container

**Comment by hirenshah** [comment]
What are you trying to run it on? I use nginx on my Synology with plpp on the Web Server.

**Comment by saitoh183** [comment]
well i can get it up and running in a docker container running nginx but the php gc is missing so i have no images (thats what i think the problem is) and if it was in a container, i could use the  [jwilder/nginx-proxy]( https://github.com/jwilder/nginx-proxy) conatiner to enable SSL with Letsencrypt. I would build one but im still trying to learn how to create a docker image with everything i need in it to run this

**Comment by Tensai75** [comment]
I only use docker in a very limited way as an user and I simply don't know how to create a docker image at all. Therefore I cannot help you.
Maybe someone else with more docker skills can provide a plpp docker image.

**Comment by saitoh183** [comment]
Ok, I will try to figure out something

**Comment by tronyx** [comment]
I built an image for you:

https://hub.docker.com/r/tronyx/docker-plpp/

Also, there was an error with some missing bootstrap font files so I added them into my forked repo. I will submit a PR if you'd like.

**Comment by Tensai75** [comment]
Hey Chris

thanks a lot for creating the docker image. I have included a link to it in the read me.

Regards, Tensai

**Comment by tronyx** [comment]
No problem, happy to help!
