### ISSUE TITLE
Error: Could not get list of libraries! Is the Plex Server online and are the plex server settings configured properly?

### ISSUE THREAD

**Issue by kauanmocelin** [Tensai75/plpp#7]
I can't access PLPP library, all configuration about my plex server is ok, ip and port.

I use PLPP with Organizr in a nginx server. PLPP is installed at: /var/www/organizr.local/html/plpp

I activeted debug mod on PLPP and i received this: http://192.168.1.107:32400/library/sections?X-Plex-Token=e919553d0ec1c69389c1e0XXXXXXX, i try to access this url directly on my browser and i received 401(access denied)..sometimes i clear all cache, cookies, configurations, etc and PLPP works, sounds like some conflict with plex token.

**Comment by engineerisaac** [comment]
Did you ever get this resolved? We are seeing this issue too.

**Comment by Tensai75** [comment]
Added an option on the settings page to reset the token stored in the user session ([v1.0.3](https://github.com/Tensai75/plpp/releases/tag/v1.0.3)).
Might solve this issue without having to clear the cache/restart the browser.
Please provide feedback if it helped.

**Comment by mykroft** [comment]
When I access the URL directly, it always come up.  But the system can not access it via the libraries menu  option.

dont know if it has anything to do with the problem, but I do have 3 local users defined in my setup.  A master allowed to make changes to everything, private - non kids movies, and videos.

suggestions?

**Comment by mykroft** [comment]
dont know if it has anything to do with the problem, but I do have 3 local users defined in my setup.  A master allowed to make changes to everything, private - non kids movies, and videos.

**Comment by engineerisaac** [comment]
That fixed the issue entirely.
