### ISSUE TITLE
Posters do not show up

### ISSUE THREAD

**Issue by aztm22** [Tensai75/plpp#8]
I just installed the plpp on my server and it runs great but it will not display any of the posters for movies or tv shows [http://a-network.ca/site/232323.jpg](http://a-network.ca/site/232323.jpg)

**Comment by Tensai75** [comment]
This can have several causes. Maybe your PHP installation is missing some libraries which are used for the image handling. Please go to Settings -> User Settings and set "Debug" to true. If you then see any PHP error messages when loading the page, please report them here. You may also check your PHP log for such error messages.

**Comment by aztm22** [comment]
none no errors at all, im running ubuntu with nginx not sure if maybe you can help me i have three of these running for each server but no pictures

**Comment by aztm22** [comment]
http://a-network.ca/site/server1/index.php

**Comment by aztm22** [comment]
i see this for each item /:/resources/movie-fanart.jpg

**Comment by Tensai75** [comment]
The pictures don't load because of a 500 server error. Please have a look into the server's log files to see which error messages are thrown.

**Comment by tronyx** [comment]
@aztm22 If you have not yet resolved this, you will need to also make sure that the Server hosting PLPP has the php-gd package installed.
