### ISSUE TITLE
connection timed out

### ISSUE THREAD

**Issue by usulbz** [Tensai75/plpp#9]
Accessing the frontpage or trying to select the libraries to display, i got this error: Connection timed out after 10000 milliseconds

PMS is on a server at home.
PLPP is on a webserver not at home.

pasting the url "http://xxxx.xxxx.xxx:32400/library/sections?X-Plex-Token=xxxxxxxxxxxxxxxxx" in the browser, it perfectly fetches all the data.

**Comment by tronyx** [comment]
Can the Server hosting PLPP reach your Home, IE: via ping? If no, that's your issue. If yes, then I would see if the Server can telnet to your Home on port 32400 to see if it's just a firewall issue.
